name: Github Audit

on:
  pull_request:
    types:
      - opened
      - edited
  push:
    branches:
      - main

jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Setup yarn
        run: npm install -g yarn
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('yarn.lock')}}
          restore-keys: node_modules-
      - name: Install node_modules
        run: yarn
        working-directory: ./extension
      - name: Build extension
        run: npm run build:chrome & npm run build:firefox & npm run build:electron
        working-directory: ./extension
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome
          path: ./extension/dist-chrome
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: ./extension/dist-firefox
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron
          path: ./extension/dist-electron
      - name: Report status
        run: echo "audit=success" >> $GITHUB_OUTPUT
